# Generated by Django 5.2.7 on 2025-10-20 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidencias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('usuario_login', models.CharField(max_length=30, unique=True)),
                ('contraseña', models.CharField(max_length=120)),
                ('rol', models.CharField(choices=[('control_interno', 'Control Interno'), ('admin_terminal', 'Administrador de Terminal'), ('admin_sistema', 'Administrador del Sistema')], max_length=20)),
                ('id_terminal', models.ForeignKey(blank=True, help_text='solo se asigna a los administradores de terminal', null=True, on_delete=django.db.models.deletion.SET_NULL, to='incidencias.terminal')),
            ],
        ),
    ]
