# Generated by Django 4.2.16 on 2025-10-20 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0002_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='contraseña',
        ),
        migrations.AddField(
            model_name='usuario',
            name='contrasena',
            field=models.CharField(default=123, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_terminal',
            field=models.ForeignKey(blank=True, help_text='Solo se asigna a administradores de terminal', null=True, on_delete=django.db.models.deletion.SET_NULL, to='incidencias.terminal'),
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='Usuarios',
        ),
    ]
