# Generated by Django 4.2.16 on 2025-11-17 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_alter_reporte_archivo_reporte_alter_reporte_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporte',
            options={'managed': False, 'verbose_name': 'Reporte', 'verbose_name_plural': 'Reportes'},
        ),
    ]
