# Generated by Django 4.2.16 on 2025-11-17 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0003_alter_reporte_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reporte',
            table='reportes',
        ),
    ]
