# Generated by Django 5.2.7 on 2025-10-20 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoleteroCajero',
            fields=[
                ('id_bc', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('usuario', models.CharField(max_length=20)),
                ('cargo', models.CharField(choices=[('boletero', 'Boletero'), ('cajero', 'Cajero')], max_length=10)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id_terminal', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_terminal', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id_incidencia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_incidencia', models.DateField()),
                ('tipo_incidencia', models.CharField(max_length=50)),
                ('motivo', models.TextField()),
                ('estado', models.CharField(max_length=20)),
                ('evidencia', models.CharField(blank=True, max_length=255, null=True)),
                ('id_bc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidencias.boleterocajero')),
            ],
        ),
    ]
