# Generated by Django 5.2.7 on 2025-10-20 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidencias', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='boleterocajero',
            name='id_terminal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidencias.terminal'),
        ),
    ]
