# Generated by Django 4.2.16 on 2025-11-17 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boleterocajero',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='incidencia',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='terminal',
            options={'managed': False},
        ),
    ]
