# Generated by Django 4.2.16 on 2025-11-17 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0003_alter_boleterocajero_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='boleterocajero',
            table='boleteros_cajeros',
        ),
        migrations.AlterModelTable(
            name='incidencia',
            table='incidencias',
        ),
        migrations.AlterModelTable(
            name='terminal',
            table='terminales',
        ),
    ]
